/*
 * PWM.c
 *
 *  Created on: Jul 1, 2022
 *      Author: Wels
 */
#include "PWM.h"

void PWM_Gpio(void)
{
	//PE9 PWM1 CH 1
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOEEN;
	GPIOE->MODER &= ~GPIO_MODER_MODER9; // RESET
	GPIOE->MODER |= GPIO_MODER_MODER9_1;// ALTERNA
	// PUSH PULL
	GPIOE->OTYPER &= ~(GPIO_OTYPER_OT9);
	// LOW SPEED
	GPIOE->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR9);
	// NO PULL UP - PULL DOWN
	GPIOE->PUPDR &= ~(GPIO_PUPDR_PUPD9);
	// PA8 -> AFRH
	// PA8 -> AF1 = TIM1 CH1
	GPIOE->AFR[1] &= ~GPIO_AFRH_AFSEL9;
	GPIOE->AFR[1] |= GPIO_AFRH_AFSEL9_0;
}

void PWM_ServoMotor(void)
{
	PWM_Gpio();
	//	CLOCK PWM
	RCC->APB2ENR |= RCC_APB2ENR_TIM1EN;
	// CUENTA ASCENDENTE
	TIM1->CR1 &= ~(TIM_CR1_DIR);
	// ALINEACIÓN IZQUIERDA
	TIM1->CR1 &= ~(TIM_CR1_CMS);
	// CLOCK DIVISION
	TIM1->CR1 &= ~(TIM_CR1_CKD);
	// PRESCALER
	TIM1->PSC = 180-1;
	// FPWM = 50Hz->20000-1
	TIM1->ARR = 20000-1;
	// MOE ENABLE
	TIM1->BDTR |= TIM_BDTR_MOE;
	// CANAL UNO HABILITADO
	TIM1->CCER |= TIM_CCER_CC1E;
	// SALIDA
	TIM1->CCMR1 &= ~(TIM_CCMR1_CC1S);
	// PWM SELECCIONADO
	TIM1->CCMR1 |= (TIM_CCMR1_OC1M_2 | TIM_CCMR1_OC1M_1);
	// DUTY CYCLE 50%
	TIM1->CCR1 = 8999;
	// ENABLE TIM1
	TIM1->CR1 |= TIM_CR1_CEN;
}

void PWM_SetDutyServo(uint16_t duty)
{
	if(duty>100){
		duty=100;
	}
	TIM1->CCR1 = (uint16_t)(TIM1->ARR + 0.0f)*(duty/100.0f);
}



